version: '3.7'

services:

  client:
    image: app-client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - app-network

  api:
    image : app-server
    ports:
      - "5000:5000"
    networks:
      - app-network


networks:
  app-network:
